export default{
    // notifications
    MARK_NOTIFICATION_AS_READ: 'MARK_NOTIFICATION_AS_READ',
    MARK_ALL_NOTIFICATIONS_AS_READ: 'MARK_ALL_NOTIFICATIONS_AS_READ',
    START_NOTIFICATION_POST: 'START_NOTIFICATION_POST',
    FINISH_NOTIFICATION_POST: 'FINISH_NOTIFICATION_POST',
    RECEIVE_NOTIFICATIONS: 'RECEIVE_NOTIFICATIONS',

    // login
    START_LOGIN: 'START_LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',

    // Profile
    CHANGE_AVATAR: 'CHANGE_AVATAR'
}